name: Publish Docker image

on:
#   release:
    # types: [published]
  workflow_dispatch:
  push:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Add version to github env
        run: |
          echo "TAG=$(python _version.py)" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jangxx/twitch-auto-recorder-3000:latest
            jangxx/twitch-auto-recorder-3000:${{ env.TAG }}
